// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Savitar.Infrastructure.Repository.EFCore;

namespace Savitar.Infrastructure.Repository.EFCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210829082817_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DevelopmentTechnologyProject", b =>
                {
                    b.Property<int>("DevelopmentTechnologiesId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.HasKey("DevelopmentTechnologiesId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("DevelopmentTechnologyProject");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "1",
                            Name = "System Administrator",
                            NormalizedName = "System Administrator"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "2",
                            Name = "Administrator",
                            NormalizedName = "Administrator"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "3",
                            Name = "Guest",
                            NormalizedName = "Guest"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Savitar.Domain.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bda824e0-409e-4e30-a82a-94a5b4b94d4c",
                            Email = "msmit@savitar.co.za",
                            EmailConfirmed = true,
                            FirstName = "Michael",
                            LastName = "Smit",
                            LockoutEnabled = false,
                            NormalizedEmail = "MSMIT@SAVITAR.CO.ZA",
                            NormalizedUserName = "MSMIT@SAVITAR.CO.ZA",
                            PasswordHash = "AQAAAAEAACcQAAAAEGEX3z1L/wAyAigS1UFRDkfbScxssOzNrQ4afBPoDGj1XFHfSQSMSt/O4v1qVY+sPw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1d00bb6a-5fb3-4971-bd67-a6d4b7bf34ac",
                            TwoFactorEnabled = false,
                            UserName = "msmit@savitar.co.za"
                        });
                });

            modelBuilder.Entity("Savitar.Domain.Models.Entities.CV.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Savitar IT Solutions"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aberdare Cables",
                            Url = "https://www.aberdare.co.za"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accutrak Pty (Ltd)",
                            Url = "https://www.accutrak.co.za"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cosoft"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Smartec Technologies"
                        });
                });

            modelBuilder.Entity("Savitar.Domain.Models.Entities.CV.DevelopmentTechnology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DevelopmentTechnologyCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FirstUse")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUse")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Proficiency")
                        .HasColumnType("int");

                    b.Property<int>("UsageFrequency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DevelopmentTechnologyCategoryId");

                    b.HasIndex("Name");

                    b.ToTable("DevelopmentTechnologies");

                    b.HasData(
                        new
                        {
                            Id = 16,
                            DevelopmentTechnologyCategoryId = 4,
                            FirstUse = new DateTime(1997, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUse = new DateTime(1999, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "AS400 Mainframe",
                            Proficiency = 0,
                            UsageFrequency = 2
                        },
                        new
                        {
                            Id = 9,
                            DevelopmentTechnologyCategoryId = 6,
                            FirstUse = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Automapper",
                            Proficiency = 3,
                            UsageFrequency = 2
                        },
                        new
                        {
                            Id = 5,
                            DevelopmentTechnologyCategoryId = 3,
                            FirstUse = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Blazor Server",
                            Proficiency = 2,
                            UsageFrequency = 3
                        },
                        new
                        {
                            Id = 6,
                            DevelopmentTechnologyCategoryId = 3,
                            FirstUse = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Blazor WebAssembly",
                            Proficiency = 2,
                            UsageFrequency = 3
                        },
                        new
                        {
                            Id = 23,
                            DevelopmentTechnologyCategoryId = 2,
                            FirstUse = new DateTime(1994, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUse = new DateTime(2010, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "C++",
                            Proficiency = 3,
                            UsageFrequency = 0
                        },
                        new
                        {
                            Id = 1,
                            DevelopmentTechnologyCategoryId = 2,
                            FirstUse = new DateTime(2001, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "C#",
                            Proficiency = 3,
                            UsageFrequency = 3
                        },
                        new
                        {
                            Id = 14,
                            DevelopmentTechnologyCategoryId = 2,
                            FirstUse = new DateTime(1995, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUse = new DateTime(2007, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Delphi",
                            Proficiency = 3,
                            UsageFrequency = 3
                        },
                        new
                        {
                            Id = 3,
                            DevelopmentTechnologyCategoryId = 3,
                            FirstUse = new DateTime(2014, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = ".NET Core",
                            Proficiency = 2,
                            UsageFrequency = 2
                        },
                        new
                        {
                            Id = 2,
                            DevelopmentTechnologyCategoryId = 3,
                            FirstUse = new DateTime(2001, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = ".NET Framework",
                            Proficiency = 3,
                            UsageFrequency = 3
                        },
                        new
                        {
                            Id = 15,
                            DevelopmentTechnologyCategoryId = 6,
                            FirstUse = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Excel",
                            Proficiency = 2,
                            UsageFrequency = 2
                        },
                        new
                        {
                            Id = 22,
                            DevelopmentTechnologyCategoryId = 4,
                            FirstUse = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Microsoft Access",
                            Proficiency = 2,
                            UsageFrequency = 1
                        },
                        new
                        {
                            Id = 12,
                            DevelopmentTechnologyCategoryId = 6,
                            FirstUse = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Postman",
                            Proficiency = 2,
                            UsageFrequency = 2
                        },
                        new
                        {
                            Id = 7,
                            DevelopmentTechnologyCategoryId = 4,
                            FirstUse = new DateTime(1998, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUse = new DateTime(2021, 8, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "SQL Server",
                            Proficiency = 3,
                            UsageFrequency = 3
                        },
                        new
                        {
                            Id = 10,
                            DevelopmentTechnologyCategoryId = 6,
                            FirstUse = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Structure Map",
                            Proficiency = 3,
                            UsageFrequency = 2
                        },
                        new
                        {
                            Id = 18,
                            DevelopmentTechnologyCategoryId = 2,
                            FirstUse = new DateTime(1997, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUse = new DateTime(2014, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Visual Basic",
                            Proficiency = 2,
                            UsageFrequency = 0
                        },
                        new
                        {
                            Id = 19,
                            DevelopmentTechnologyCategoryId = 2,
                            FirstUse = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUse = new DateTime(2010, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Visual Basic.NET",
                            Proficiency = 2,
                            UsageFrequency = 3
                        },
                        new
                        {
                            Id = 11,
                            DevelopmentTechnologyCategoryId = 1,
                            FirstUse = new DateTime(2003, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Visual Studio",
                            Proficiency = 3,
                            UsageFrequency = 3
                        },
                        new
                        {
                            Id = 20,
                            DevelopmentTechnologyCategoryId = 3,
                            FirstUse = new DateTime(2003, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUse = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Web Services",
                            Proficiency = 2,
                            UsageFrequency = 0
                        },
                        new
                        {
                            Id = 24,
                            DevelopmentTechnologyCategoryId = 5,
                            FirstUse = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Entity Framework",
                            Proficiency = 3,
                            UsageFrequency = 2
                        },
                        new
                        {
                            Id = 8,
                            DevelopmentTechnologyCategoryId = 4,
                            FirstUse = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUse = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PostgreSQL",
                            Proficiency = 0,
                            UsageFrequency = 0
                        },
                        new
                        {
                            Id = 25,
                            DevelopmentTechnologyCategoryId = 5,
                            FirstUse = new DateTime(2014, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUse = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "nHibernate",
                            Proficiency = 2,
                            UsageFrequency = 0
                        },
                        new
                        {
                            Id = 21,
                            DevelopmentTechnologyCategoryId = 3,
                            FirstUse = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Web/REST API",
                            Proficiency = 3,
                            UsageFrequency = 3
                        },
                        new
                        {
                            Id = 13,
                            DevelopmentTechnologyCategoryId = 2,
                            FirstUse = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUse = new DateTime(1993, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Turbo Pascal",
                            Proficiency = 3,
                            UsageFrequency = 2
                        },
                        new
                        {
                            Id = 26,
                            DevelopmentTechnologyCategoryId = 2,
                            FirstUse = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Javascript",
                            Proficiency = 3,
                            UsageFrequency = 3
                        },
                        new
                        {
                            Id = 27,
                            DevelopmentTechnologyCategoryId = 6,
                            FirstUse = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUse = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RabbitMQ",
                            Proficiency = 0,
                            UsageFrequency = 0
                        },
                        new
                        {
                            Id = 28,
                            DevelopmentTechnologyCategoryId = 2,
                            FirstUse = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUse = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Python",
                            Proficiency = 0,
                            UsageFrequency = 0
                        },
                        new
                        {
                            Id = 29,
                            DevelopmentTechnologyCategoryId = 3,
                            FirstUse = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUse = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "VUE",
                            Proficiency = 0,
                            UsageFrequency = 0
                        },
                        new
                        {
                            Id = 30,
                            DevelopmentTechnologyCategoryId = 1,
                            FirstUse = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUse = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PyCharm",
                            Proficiency = 0,
                            UsageFrequency = 0
                        },
                        new
                        {
                            Id = 31,
                            DevelopmentTechnologyCategoryId = 1,
                            FirstUse = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "VS Code",
                            Proficiency = 2,
                            UsageFrequency = 2
                        },
                        new
                        {
                            Id = 32,
                            DevelopmentTechnologyCategoryId = 6,
                            FirstUse = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PowerShell",
                            Proficiency = 3,
                            UsageFrequency = 2
                        },
                        new
                        {
                            Id = 33,
                            DevelopmentTechnologyCategoryId = 1,
                            FirstUse = new DateTime(2005, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUse = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Borland Developer Studio",
                            Proficiency = 3,
                            UsageFrequency = 0
                        },
                        new
                        {
                            Id = 34,
                            DevelopmentTechnologyCategoryId = 6,
                            FirstUse = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUse = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Apache Spark",
                            Proficiency = 0,
                            UsageFrequency = 0
                        },
                        new
                        {
                            Id = 35,
                            DevelopmentTechnologyCategoryId = 6,
                            FirstUse = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Docker",
                            Proficiency = 0,
                            UsageFrequency = 1
                        },
                        new
                        {
                            Id = 4,
                            DevelopmentTechnologyCategoryId = 3,
                            FirstUse = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = ".NET 5",
                            Proficiency = 2,
                            UsageFrequency = 3
                        },
                        new
                        {
                            Id = 36,
                            DevelopmentTechnologyCategoryId = 6,
                            FirstUse = new DateTime(2021, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MudBlazor",
                            Proficiency = 2,
                            UsageFrequency = 2
                        });
                });

            modelBuilder.Entity("Savitar.Domain.Models.Entities.CV.DevelopmentTechnologyCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("DevelopmentTechnologyCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IDE"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Language"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Framework"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Database"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ORM"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tool"
                        });
                });

            modelBuilder.Entity("Savitar.Domain.Models.Entities.CV.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Name");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            Description = "Wanting to learn the new Microsoft Blazor technology, I decided to build this site using the technology to gain some needed experience.<br/><br/>\r\n                        The aim is to introduce different concepts over time, add tools, and just generarlly showcase what Blazor is capable of, and what I can do with it.",
                            Name = "# Savitar WebAssembly and Server : This website :)"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 1,
                            Description = "The company already had a web application built off DotNetNuke. I simply built them a DNN module that facilitated online payments.",
                            Name = "dBit : MWeb Payment Module"
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 1,
                            Description = "Application written to enable the setting up, tracking and cash reconciliation of Nedbank ATM canisters around South Africa.\r\nI wrote the web application for the system that enabled users to setup the canisters, track their locations, monitor the status and reconcile cash-up once the canisters arrived at the cash centre.",
                            Name = "Absolute Systems"
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 1,
                            Description = "Contracted to Adcheck for a number of projects that I am unable to elaborate on due to an NDA in effect",
                            Name = "Adcheck Contractor"
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 1,
                            Description = "<ul>\r\n    <li>Traffic violation system installed on freeways and at intersections, and any other deemed to be an area speed or red robot violations are committed.</li>\r\n    <li>Speed is determined based on data fed to the system via pizzo lines laid under the road, or a laser system mounted to the camera unit. The system communicates with a Canon camera of image taking.</li>\r\n    <li>Red robot status is determined by data fed to the system via the traffic lights.</li>\r\n    <li>System can handle red robot violations, speed violations or both.</li>\r\n    <li>System is user configurable for different speed triggers, pizzo line distances, laser calibration, camera flash settings, day/night setup and camera capture delay.</li>\r\n    <li>Speed can determine when cars or trucks are passing over the lines. This is needed so the side of a truck is not snapped when a truck commits a violation. A laser is used to determine if there is a “blockage”. If so, the snap is delayed until the blockage flag is reset.</li>\r\n    <li>Data is stored internally on the camera in a SQL Server 2005 Express database and provides statistics of violations per hour, line passings per hour, etc…</li>\r\n    <li>Data is retrieved by a traffic office by inserting a memory stick into the camera USB port. The system automatically detects the memory stick and transfers data to the memory stick.</li>\r\n    <li>All images and data are stored in files encrypted using triple DES encryption. Data is overlaid on the images before storage as well as being stored alongside the images in the file for retrieval later.</li>\r\n</ul>",
                            Name = "Artemis Red Robot"
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 1,
                            Description = "<ul>\r\n    <li>Similar application to Artemis Red Robot, but this version streams feed from a video camera and freezes the image when a violation is recorded. The system is also a mobile system. The PC is embedded in a hardened plastic suitcase and powered off a 12v battery.</li>\r\n    <li>Speed is recorded via a hand held or tripod mounted laser.</li>\r\n    <li>Red robot violations cannot be handled by this system.</li>\r\n</ul>",
                            Name = "Artemis Mobile Edition"
                        },
                        new
                        {
                            Id = 7,
                            ClientId = 1,
                            Description = "Company web application for advertising athletic events, handling athlete profiles, athlete event registration and displaying event results.\r\n\r\nThis web application was content managed to enable ASA to add and maintain their own pages without the need for a developer.\r\n\r\nSavitar IT was also responsible for the hosting and maintenance of this website for a few years.",
                            Name = "Athletics South Africa"
                        },
                        new
                        {
                            Id = 8,
                            ClientId = 1,
                            Description = "Build the Point of Sale module that is integrated in the Brilliant Account package.",
                            Name = "Brilliant Accounting - Point of Sale"
                        },
                        new
                        {
                            Id = 9,
                            ClientId = 1,
                            Description = "Canoe Kayak World required a website to display products sold in store and to advertise events organized.",
                            Name = "Canoe Kayak World"
                        },
                        new
                        {
                            Id = 10,
                            ClientId = 1,
                            Description = "<ul>\r\n    <li>Web application for monitoring winning lotto numbers and notifies end users of winning number combinations.</li>\r\n    <li>End users would SMS the numbers they required notififcation for to a 5 digit number (like advertised on TV). The SMS is sent via the ClickATell gateway to the website and loaded into the database against the users cell number. Depending on the code entered, the end user would receive notifications for 2, 4 or 8 week periods.</li>\r\n    <li>The web application owner would load the winning numbers after each draw. If any of the notifications in the system matched the winning numbers, an SMS would be sent to the end users via the ClickATell gateway notifying them of their winning numbers.</li>\r\n</ul>",
                            Name = "CheckMyTicket"
                        },
                        new
                        {
                            Id = 11,
                            ClientId = 1,
                            Description = "<ul>\r\n                            <li>Web application catering to both the employer and employee. The system ran very much in the same way PNet does but with some unique ideas provided by the client. This system was also targeted initially at the Nigerian market with the aim of going world wide at a later date.</li>\r\n                            <li>Users gained access to the system via scratch card numbers. The scratch cards are provided at various outlets around Nigeria. The employee user is able to register an account and setup their CV. They are however not able to print the CV or submit to potential employers until a valid scratch card number has been entered.</li>\r\n                            <li>Scratch card numbers are imported into the system via a flat file CSV format. These numbers are then used to verify the numbers entered in by the end user.</li>\r\n                            <li>When the CV information has been input, the end user is then able to locate potential employers based on matching criteria and similarly, employers are able to locate employees via a similar mechanism.</li>\r\n                        </ul>",
                            Name = "CV Magic Worldwide"
                        },
                        new
                        {
                            Id = 12,
                            ClientId = 1,
                            Description = "Dawn wing reached a point where their in-house software had too many problems for the software to be usable. I was contracted to assist them with ironing out the problems and getting the software to a stable position again.",
                            Name = "Dawn Wing"
                        },
                        new
                        {
                            Id = 13,
                            ClientId = 1,
                            Description = "<ul>\r\n    <li>Winforms application to handle insurance contracts sold to owners of exotic cars like Ferrari, Lamborghini, etc...</li>\r\n    <li>The system tracked teh insurance value and start/end dates.</li>\r\n    <li>When all data was loaded into the system, the system generates a contract for the client. Contract is signed, scanned back into the system and linked to the clients profile.</li>\r\n</ul>",
                            Name = "Ferdinandplan"
                        },
                        new
                        {
                            Id = 14,
                            ClientId = 1,
                            Description = "This was a system owned / maintained by Savitar IT Solutions for about 8 years, and in use in the hospitality industry.\r\n<ul>\r\n    <li>Targets both the Franchisee and Franchisor.</li>\r\n    <li>Multiple levels of security and access. Franchisee, franchisor and administrator. Each of these levels could further define their own security and permissions based on needs.</li>\r\n    <li>Franchisees could manually capture their daily sales, or upload them automatically using our RESTful API. Stock, supplier, etc... information was manually captured.</li>\r\n    <li>Franchisors could monitor sales, reconcile sales information, generate franshisee fees (and invoice), provide upper management GP reports, setup menu items (by store, group or region), manage stock (including pricing across regions), suppliers, agents, etc...</li>\r\n</ul>",
                            Name = "Franchise Management System"
                        },
                        new
                        {
                            Id = 15,
                            ClientId = 1,
                            Description = "Web application to display the companies profile and related products.",
                            Name = "Hygeria"
                        },
                        new
                        {
                            Id = 16,
                            ClientId = 1,
                            Description = "Simple user control that plugged into Incredible Connection's existing intranet that would scroll data by branch. Data was supplied via XML.",
                            Name = "Incredible Connection Marquee"
                        },
                        new
                        {
                            Id = 17,
                            ClientId = 1,
                            Description = "<ul>\r\n    <li>Winforms application for cataloging and provide lookup/search functionality of various media.</li>\r\n    <li>In addition, when audio CD's are inserted, the ID of the disc is read and a lookup done to the CD-DB API to retrieve information about the disc.</li>\r\n    <li>Media can be played directly out of Media Magic. All the user has to do is search for the media they want to listen to, then insert the </li>\r\n    <li>System had the ability to rate titles to facilitate lookups by tempo, genre, year, etc...</li>\r\n</ul>",
                            Name = "Media Magic"
                        },
                        new
                        {
                            Id = 18,
                            ClientId = 1,
                            Description = "Basic system to handle the management of recycled paper and exporting data to JD Edwards.",
                            Name = "Mondi Recyling RMS"
                        },
                        new
                        {
                            Id = 19,
                            ClientId = 1,
                            Description = "MWeb Business outsourced a number of web applications to us to do on their behalf. Unable to disclose further information due to an NDA, but a noteworthy entry anyway.",
                            Name = "MWeb Business"
                        },
                        new
                        {
                            Id = 20,
                            ClientId = 1,
                            Description = "Web application to display companies profile and products available",
                            Name = "Pacify"
                        },
                        new
                        {
                            Id = 21,
                            ClientId = 1,
                            Description = "<ul>\r\n    <li>Web application for handling timesheets and time invoicing.</li>\r\n    <li>System catered to companies, staff and users.</li>\r\n    <li>Invoices auto or manually emailed. Users could log in to manage/view timesheets, invoices and payments.</li>    \r\n</ul>",
                            Name = "Project Watch"
                        },
                        new
                        {
                            Id = 22,
                            ClientId = 1,
                            Description = "Converted the PSCBC web application from .NET 1.1 to .NET 3.5, updated SQL Server, and migrated data.",
                            Name = "PSCBC"
                        },
                        new
                        {
                            Id = 23,
                            ClientId = 1,
                            Description = "Web application to handle product information and warranty returns for the RoadAngle GPS product.",
                            Name = "RoadAngle"
                        },
                        new
                        {
                            Id = 24,
                            ClientId = 1,
                            Description = "Application for importing and analysing data fed into the system via XML files, to assist them in determining the structural integrity of the panel's worked in by the miners in the mine. NDA prevents further information.",
                            Name = "Rockwatch.NET"
                        },
                        new
                        {
                            Id = 25,
                            ClientId = 1,
                            Description = "<ul>\r\n    <li>Winforms application to assist in the manufacturing of plastic materials at Roto-Plastics.</li>\r\n    <li>Enables end users to create recipes based on plastics, colours, dy, material and design.</li>\r\n</ul>",
                            Name = "Roto-Platics"
                        },
                        new
                        {
                            Id = 26,
                            ClientId = 1,
                            Description = "Web application for handling the distribution of radio controlled helicopters and accessories.\r\n<ul>\r\n    <li>Dual purpose website for both distributors and vendors with pricing to match login.</li>\r\n    <li>The system handles ordering, checkout and shipping tracking. Stock control is maintained on invoice and stock levels are automatically adjusted</li>\r\n</ul>",
                            Name = "Savitar RC"
                        },
                        new
                        {
                            Id = 27,
                            ClientId = 1,
                            Description = "Web application to display company information and available products",
                            Name = "Signal Systems"
                        },
                        new
                        {
                            Id = 28,
                            ClientId = 1,
                            Description = "Simple web application advertising the companies services",
                            Name = "Signature Placements"
                        },
                        new
                        {
                            Id = 29,
                            ClientId = 1,
                            Description = "<ul>\r\n    <li>Windows application for the SABC marketing department. The application handled the cataloging and retrieval of adverts that were recorded for use on the various radio stations.</li>\r\n    <li>A custom database backend was developed for use in this application employing the use of C++ structs. The custom database also supported indexing for fast retrieval.</li>\r\n</ul>",
                            Name = "SmartAd"
                        },
                        new
                        {
                            Id = 30,
                            ClientId = 1,
                            Description = "eCommerce web application for advertising, leasing and selling movies and video games.",
                            Name = "Videotown"
                        },
                        new
                        {
                            Id = 31,
                            ClientId = 1,
                            Description = "This application was written back in the Windows For Workgroups days as a frontend to the command line only tool, WinAce. It offered a graphical user interface to the end user for configuring archive settings, storage location and encryption mechanism. Data was then fed via the cmd line to Winace to do the actual work.",
                            Name = "Winace Frontend"
                        },
                        new
                        {
                            Id = 32,
                            ClientId = 1,
                            Description = "<ul>\r\n    <li>Winamp 2.x plugin</li>\r\n    <li>Hooks all winamp windows and log internal window messages sent between the various Winamp windows. The plugin is a developer tool to assist plugin developers of Winamp plugins to easily work out which messages to intercept.\r\nThis was released free to the community and assisted me with further Winamp development.</li>\r\n</ul>",
                            Name = "Winamp Monitor"
                        },
                        new
                        {
                            Id = 33,
                            ClientId = 1,
                            Description = "<ul>\r\n    <li>Winamp 2.x plugin</li>\r\n    <li>Winamp had no mechanism to rate tracks or set tempo. This plug-in enabled a user to rate tracks and set the tempo\r\nvia global hot keys (Winamp did not need focus to handle the hotkeys). Tracks could then be loaded via these\r\nsettings by the end user.</li>\r\n</ul>",
                            Name = "Winamp Ratings"
                        },
                        new
                        {
                            Id = 34,
                            ClientId = 1,
                            Description = "eCommerce web application for radio controlled helicopters and accessories.",
                            Name = "Xheli"
                        },
                        new
                        {
                            Id = 35,
                            ClientId = 2,
                            Description = "Management required production information from the factory floor. \r\nThe IT Manager wanted a system coded in VB, but the order of the required software was taking time, so I made a plan using Microsoft Excel (VBA) to extract the information required from the AS400, generate graphs and tables, and dump it on the companies LAN.\r\n\r\nThis system remained in use for around 15 years after I moved on!\r\n\r\nBeing the first PC developer in the company, I was also responsible for assisting with network installation, PC builds, etc...",
                            Name = "AS400ToIntranet"
                        },
                        new
                        {
                            Id = 36,
                            ClientId = 3,
                            Description = "Smartrail combines state of the art in-line weighbridge technology with low power RFiD tracking technology to give you real time accounting of your production volumes available on surface.\r\n\r\n    I was involved with the server development. This consisted of a Windows Service and IIS Website. The Windows Service took care or ETL and maintenance tasks, and the website for master data, reporting, etc...\r\n\r\nWhen this project started in 2005, my client only had installation files for the first version of their software. It was a Winforms application on the .NET 1 framework. I reverse engineered the system and extracted the required sources. The system was then upgraded to .NET Framework 2, and later to a web application. It then got a re-write about 6 years ago to the system it is currently.",
                            Name = "Smartrail",
                            Url = "https://www.accutrak.co.za/our-products-2/smartrail"
                        },
                        new
                        {
                            Id = 37,
                            ClientId = 3,
                            Description = "Minegaze is a GPS based tracking and weighing solution for the surface or open cast trackless mining environments. Minegaze makes use of the GSM network to upload collected data into the cloud with the objective of optimising production.",
                            Name = "Minegaze",
                            Url = "https://www.accutrak.co.za/our-products-2/minegaze/"
                        },
                        new
                        {
                            Id = 38,
                            ClientId = 3,
                            Description = "Accuchip is an RFid tracking solution for material cars and general rolling stock. This is an RFid solution that can be applied to various rolling stock items and high value equipment to provide proximity detection and location reporting.",
                            Name = "Accuchip",
                            Url = "https://www.accutrak.co.za/our-products-2/accuchip/"
                        },
                        new
                        {
                            Id = 39,
                            ClientId = 3,
                            Description = "Trucktrak is a production management system designed specifically for mechanised underground mining operations. Since there is no GPS available underground from which to obtain position, Trucktrak makes use of discretely distributed long life battery operated beacons to obtain position.",
                            Name = "Trucktrak",
                            Url = "https://www.accutrak.co.za/our-products-2/outset/"
                        },
                        new
                        {
                            Id = 40,
                            ClientId = 4,
                            Description = "<ul>\r\n                            <li>Point Of Sale solution serving the hospitality industry. In use by Steers Holdings (Steers, Debonairs, etc..), Fishaways, Something Fishy, Hotdog Café, Scooters, and more.</li>\r\n                            <li>The system had a front end workstation for the till operators to perform sales and a back office for management to generate sales reports, setup menus, and more.</li>\r\n                            <li>All sales were uploaded nightly at the Alphapos Enterprise server – via FTP - to be imported into a data warehouse solution to enable the franchisor to view sales statistics for all franchises and outlets country wide.</li>\r\n                            <li>The application is extremely feature rich and catered to both the franchisee and franchisor needs.</li>\r\n                        </ul>",
                            Name = "Aura"
                        },
                        new
                        {
                            Id = 41,
                            ClientId = 5,
                            Description = "This is a pre-paid airtime vending system.                            \r\n                            <ul>\r\n                                <li>Vending machines are installed around the country with an interface to enable customers to purchase pre-paid airtime.</li>\r\n                                <li>The vending machine communicates with a server via GPRS/EDGE/3D/HSDPA depending on the signal available at the installed location.</li>\r\n                                <li>Accounts for the vending machine owner are maintained on the server and data is synchronized with the vending machine from time to time.</li>\r\n                                <li>All vending machines are loaded with enough stock to last 2 days. As soon as the stock levels for any product reach 8 hours, the vending machine uploads all sales, and downloads new stock to replenish its-self based on items needed to see it through for the next 2 days.The quantities are determined by calculating average daily sales over the last 14 days. This prevents the terminal from having too little stock and therefore connecting too often or having too much thereby preventing sales from being uploaded regularly.</li>\r\n                                <li>Vending machines use Web Services via the SOAP protocol to communicate with the server.</li>\r\n                                <li>The service side has a complete management web interface to enable staff to setup vending machines, deploy settings to vending machines, manage accounts, funds, import stock, generate GP reports, etc…</li>\r\n                                <li>The server solution had to calculate commissions for account holders based on sales and pre-configured percentage settings.Account holders were also able to login to the web frontend to view sales statistics, draw reports and support queries.</li>\r\n                            </ul>",
                            Name = "Top-It-Up"
                        },
                        new
                        {
                            Id = 42,
                            ClientId = 5,
                            Description = "<ul>\r\n    <li>System to handle the management of starter packs sold to distributors, then to vendors - and generated commission.</li>\r\n    <li>Allows for distributor and vendor login to enable the rendering of reports for cash balances, stock orders, commissions generated, payments made, etc...</li>\r\n    <li>Starter packs are sold by CellC to a distributor (Hi-Fi Corp, etc...). The stock is sent to the system via flat file and loaded into SQL Server. Vendors then purchase the stock at Point Of Sale terminals at the distributor, with communications via SOAP Web Services in real time.</li>    \r\n</ul>",
                            Name = "CellC Distributor / Vendor Management System"
                        });
                });

            modelBuilder.Entity("Savitar.Domain.Models.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "<p>Specialising in cross platform .NET technologies, we are full stack devs for hire.</p>\r\n<br />\r\n<p>You can purchase time in a multitude of flexible ways, including...</p>\r\n<ul>\r\n    <li>Per Module</li>\r\n    <li>Per Project</li>    \r\n    <li>Per Hour</li>\r\n    <li>1 or more days per week - 1 or more weeks per month (most common). We agree on the pre-booked time and enter into a retainer. The per hour rate is also reduced relative to the kind of time booked in this arrangement.</li>\r\n</ul>\r\n<br />\r\n<p>Your invoice will come from Savitar IT (VAT registered).</p>",
                            Title = "Software Development Services"
                        },
                        new
                        {
                            Id = 2,
                            Description = "From the ground up, we can build you a new system adhering to the most current standards and specifications and on top of the latest technologies.",
                            Title = "Complete Systems"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Having many years experience in a multitude of languages and frameworks, we can assist with upgrading legacy language/framework systems to more modern languages and frameworks.\r\n<br/><br/>\r\n<b>Use Cases</b>\r\n<ul>\r\n    <li>Angular / React / Vue TO Blazor WebAssembly</li>\r\n    <li>WPF (Windows Presentation Foundation) or Silverlight to Blazor (WebAssembly or Server)</li>    \r\n    <li>.NET Framework TO .NET 5</li>\r\n    <li>C / C++ / Delphi / Visual Basic TO C#</li>\r\n    <li>Desktop application to Web application</li>\r\n</ul>",
                            Title = "Conversions/Upgrades"
                        },
                        new
                        {
                            Id = 4,
                            Description = "We can help your juniors accelerate their learning curves. We love to talk and teach code!",
                            Title = "Mentoring"
                        });
                });

            modelBuilder.Entity("DevelopmentTechnologyProject", b =>
                {
                    b.HasOne("Savitar.Domain.Models.Entities.CV.DevelopmentTechnology", null)
                        .WithMany()
                        .HasForeignKey("DevelopmentTechnologiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Savitar.Domain.Models.Entities.CV.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Savitar.Domain.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Savitar.Domain.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Savitar.Domain.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Savitar.Domain.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Savitar.Domain.Models.Entities.CV.DevelopmentTechnology", b =>
                {
                    b.HasOne("Savitar.Domain.Models.Entities.CV.DevelopmentTechnologyCategory", "DevelopmentTechnologyCategory")
                        .WithMany("Technologies")
                        .HasForeignKey("DevelopmentTechnologyCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevelopmentTechnologyCategory");
                });

            modelBuilder.Entity("Savitar.Domain.Models.Entities.CV.Project", b =>
                {
                    b.HasOne("Savitar.Domain.Models.Entities.CV.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Savitar.Domain.Models.Entities.CV.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Savitar.Domain.Models.Entities.CV.DevelopmentTechnologyCategory", b =>
                {
                    b.Navigation("Technologies");
                });
#pragma warning restore 612, 618
        }
    }
}
